apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
  {{- include "helm.selectorLabels" . | nindent 5 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}